import 'package:fluttersdk_magic/fluttersdk_magic.dart';

/// Order model.
///
/// Generated by Magic CLI.
class Order extends Model with HasTimestamps, InteractsWithPersistence {
  /// The table associated with the model.
  @override
  String get table => 'orders';

  /// The API resource for remote operations.
  @override
  String get resource => 'order';

  /// The attributes that are mass assignable.
  @override
  List<String> get fillable => [
    'payment_method',
    'payment_date',
    'shipped_date',
    'total',
    'tax_amount',
    'shipping_amount',
    'subtotal',
    'customer_id',
    'payment_id',
    'order_items'
  ];

  /// The attributes that should be cast.
  @override
  Map<String, String> get casts => {
    'payment_date': 'datetime',
    'shipped_date': 'datetime',
    'total': 'double',
    'tax_amount': 'double',
    'shipping_amount': 'double',
    'subtotal': 'double',
    'customer_id': 'int',
    'payment_id': 'int',
    'order_items': 'json'
  };

  // ---------------------------------------------------------------------------
  // Typed Accessors
  // ---------------------------------------------------------------------------

  /// Get the payment_method value.
  String? get paymentMethod => getAttribute('payment_method') as String?;
  set paymentMethod(String? value) => setAttribute('payment_method', value);

  /// Get the payment_date value.
  Carbon? get paymentDate => getAttribute('payment_date') as Carbon?;
  set paymentDate(dynamic value) => setAttribute('payment_date', value);

  /// Get the shipped_date value.
  Carbon? get shippedDate => getAttribute('shipped_date') as Carbon?;
  set shippedDate(dynamic value) => setAttribute('shipped_date', value);

  /// Get the total value.
  double? get total => getAttribute('total') as double?;
  set total(double? value) => setAttribute('total', value);

  /// Get the tax_amount value.
  double? get taxAmount => getAttribute('tax_amount') as double?;
  set taxAmount(double? value) => setAttribute('tax_amount', value);

  /// Get the shipping_amount value.
  double? get shippingAmount => getAttribute('shipping_amount') as double?;
  set shippingAmount(double? value) => setAttribute('shipping_amount', value);

  /// Get the subtotal value.
  double? get subtotal => getAttribute('subtotal') as double?;
  set subtotal(double? value) => setAttribute('subtotal', value);

  /// Get the customer_id value.
  int get customerId => (getAttribute('customer_id') ?? 0) as int;
  set customerId(int value) => setAttribute('customer_id', value);

  /// Get the payment_id value.
  int get paymentId => (getAttribute('payment_id') ?? 0) as int;
  set paymentId(int value) => setAttribute('payment_id', value);

  /// Get the order_items value.
  Map<String, dynamic>? get orderItems => getAttribute('order_items') as Map<String, dynamic>?;
  set orderItems(Map<String, dynamic>? value) => setAttribute('order_items', value);

  // ---------------------------------------------------------------------------
  // Static Helpers
  // ---------------------------------------------------------------------------

  /// Find a Order by ID.
  static Future<Order?> find(dynamic id) =>
      InteractsWithPersistence.findById<Order>(id, Order.new);

  /// Get all Orders.
  static Future<List<Order>> all() =>
      InteractsWithPersistence.allModels<Order>(Order.new);
}
