import 'package:fluttersdk_magic/fluttersdk_magic.dart';

/// OrderItem model.
///
/// Generated by Magic CLI.
class OrderItem extends Model with HasTimestamps, InteractsWithPersistence {
  /// The table associated with the model.
  @override
  String get table => 'order_items';

  /// The API resource for remote operations.
  @override
  String get resource => 'order_item';

  /// The attributes that are mass assignable.
  @override
  List<String> get fillable => ['order_item', 'product_id', 'price'];

  /// The attributes that should be cast.
  @override
  Map<String, String> get casts => {
    'price': 'double',
    'product_id': 'int',
    'order_id': 'int',
  };

  // ---------------------------------------------------------------------------
  // Typed Accessors
  // ---------------------------------------------------------------------------

  // Add your typed getters/setters here, for example:
  //
  // String? get name => getAttribute('name') as String?;
  // set name(String? value) => setAttribute('name', value);

  int? get productId => getAttribute('product_id') as int?;
  set productId(int? value) => setAttribute('product_id', value);

  double? get price => getAttribute('price') as double?;
  set price(double? value) => setAttribute('price', value);

  // ---------------------------------------------------------------------------
  // Static Helpers
  // ---------------------------------------------------------------------------

  /// Find a OrderItem by ID.
  static Future<OrderItem?> find(dynamic id) =>
      InteractsWithPersistence.findById<OrderItem>(id, OrderItem.new);

  /// Get all OrderItems.
  static Future<List<OrderItem>> all() =>
      InteractsWithPersistence.allModels<OrderItem>(OrderItem.new);
}
