import 'package:fluttersdk_magic/fluttersdk_magic.dart';

/// ProductType model.
///
/// Generated by Magic CLI.
class ProductType extends Model with HasTimestamps, InteractsWithPersistence {
  /// The table associated with the model.
  @override
  String get table => 'product_types';

  /// The API resource for remote operations.
  @override
  String get resource => 'product_type';

  /// The attributes that are mass assignable.
  @override
  List<String> get fillable => [];

  /// The attributes that should be cast.
  @override
  Map<String, String> get casts => {};

  // ---------------------------------------------------------------------------
  // Typed Accessors
  // ---------------------------------------------------------------------------

  // Define your fillable and casts above, then run:
  //   magic make:model-types ProductType
  //
  // Or add manually:
  //   String? get name => getAttribute('name') as String?;
  //   set name(String? value) => setAttribute('name', value);

  // ---------------------------------------------------------------------------
  // Static Helpers
  // ---------------------------------------------------------------------------

  /// Find a ProductType by ID.
  static Future<ProductType?> find(dynamic id) =>
      InteractsWithPersistence.findById<ProductType>(id, ProductType.new);

  /// Get all ProductTypes.
  static Future<List<ProductType>> all() =>
      InteractsWithPersistence.allModels<ProductType>(ProductType.new);
}
