import 'package:flutter/material.dart';
import 'package:fluttersdk_magic/fluttersdk_magic.dart';

import '../../resources/views/product_type/index_view.dart';
import '../../resources/views/product_type/show_view.dart';
import '../../resources/views/product_type/create_view.dart';
import '../../resources/views/product_type/edit_view.dart';

/// ProductType Resource Controller.
///
/// Generated by Magic CLI.
class ProductTypeController extends MagicController
    with MagicStateMixin<List<dynamic>> {
  /// Singleton accessor with lazy registration.
  static ProductTypeController get instance =>
      Magic.findOrPut(ProductTypeController.new);

  // ---------------------------------------------------------------------------
  // Resource Actions (CRUD)
  // ---------------------------------------------------------------------------

  /// GET /product_type - Display a listing of items.
  Widget index() {
    if (isEmpty) load();
    return const ProductTypeIndexView();
  }

  /// GET /product_type/create - Show the form for creating a new item.
  Widget create() => const ProductTypeCreateView();

  /// GET /product_type/:id - Display the specified item.
  Widget show(String id) => const ProductTypeShowView();

  /// GET /product_type/:id/edit - Show the form for editing the item.
  Widget edit(String id) => const ProductTypeEditView();

  // ---------------------------------------------------------------------------
  // Business Logic
  // ---------------------------------------------------------------------------

  /// Load all items.
  Future<void> load() async {
    // TODO: Implement
  }

  /// Store a newly created item.
  Future<void> store(Map<String, dynamic> data) async {
    // TODO: Implement
  }

  /// Update the specified item.
  Future<void> update(String id, Map<String, dynamic> data) async {
    // TODO: Implement
  }

  /// Remove the specified item.
  Future<void> destroy(String id) async {
    // TODO: Implement
  }
}
