import 'package:flutter_test/flutter_test.dart';
import 'package:magic/src/cli/helpers/main_dart_scaffold_detector.dart';

/// Full flutter create scaffold source — all 4 markers present.
const String _fullScaffoldSource = '''
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Text('You have pushed the button \$_counter times.'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
      ),
    );
  }
}
''';

/// Source with exactly 3 markers: _MyHomePageState, _counter, MyHomePage (no UI string).
const String _threeMarkerSource = '''
class MyHomePage extends StatefulWidget {
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
}
''';

/// Source with exactly 2 markers: MyHomePage + _counter only.
const String _twoMarkerSource = '''
class MyHomePage extends StatefulWidget {}

int _counter = 0;
''';

/// Source with no markers at all — user wrote from scratch.
const String _emptyStyleSource = '''
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: Scaffold());
  }
}
''';

/// Source where MyHomePage appears only inside a comment.
/// Per the accepted limitation documented in [MainDartScaffoldDetector],
/// comment markers still count toward the threshold.
const String _commentOnlyMyHomePageSource = '''
// This file was inspired by MyHomePage from the flutter create scaffold.
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}
''';

/// Source that is completely empty.
const String _emptySource = '';

void main() {
  group('MainDartScaffoldDetector.isFlutterCreateScaffold', () {
    test('returns true when all 4 markers are present', () {
      expect(
        MainDartScaffoldDetector.isFlutterCreateScaffold(_fullScaffoldSource),
        isTrue,
      );
    });

    test('returns true when exactly 3 markers are present', () {
      expect(
        MainDartScaffoldDetector.isFlutterCreateScaffold(_threeMarkerSource),
        isTrue,
      );
    });

    test('returns false when exactly 2 markers are present', () {
      expect(
        MainDartScaffoldDetector.isFlutterCreateScaffold(_twoMarkerSource),
        isFalse,
      );
    });

    test(
      'returns false when 0 markers are present (user wrote from scratch)',
      () {
        expect(
          MainDartScaffoldDetector.isFlutterCreateScaffold(_emptyStyleSource),
          isFalse,
        );
      },
    );

    test('returns false for completely empty source', () {
      expect(
        MainDartScaffoldDetector.isFlutterCreateScaffold(_emptySource),
        isFalse,
      );
    });

    test('returns false when only MyHomePage appears in a comment '
        '(1 marker — below threshold, accepted limitation)', () {
      expect(
        MainDartScaffoldDetector.isFlutterCreateScaffold(
          _commentOnlyMyHomePageSource,
        ),
        isFalse,
      );
    });

    test(
      'returns true for a comments-only counter app where all 4 markers appear in comments',
      () {
        const source = '''
// class MyHomePage widget generated by flutter create.
// class _MyHomePageState manages state.
// int _counter = 0; tracks button presses.
// You have pushed the button is displayed in the UI.
''';
        expect(
          MainDartScaffoldDetector.isFlutterCreateScaffold(source),
          isTrue,
        );
      },
    );
  });
}
