import 'package:magic/magic.dart';

import '../models/product_type.dart';

/// ProductTypePolicy
///
/// Defines authorization rules for ProductType resources.
/// Generated by Magic CLI.
class ProductTypePolicy extends Policy {
  @override
  void register() {
    Gate.define('view-product_type', view);
    Gate.define('create-product_type', create);
    Gate.define('update-product_type', update);
    Gate.define('delete-product_type', delete);
  }

  /// Determine if the user can view the ProductType.
  bool view(Model user, ProductType productType) {
    // TODO: Implement your authorization logic
    return true;
  }

  /// Determine if the user can create a ProductType.
  bool create(Model user, ProductType? productType) {
    // TODO: Implement your authorization logic
    return true;
  }

  /// Determine if the user can update the ProductType.
  bool update(Model user, ProductType productType) {
    // TODO: Implement your authorization logic
    return true;
  }

  /// Determine if the user can delete the ProductType.
  bool delete(Model user, ProductType productType) {
    // TODO: Implement your authorization logic
    return true;
  }
}
