import 'package:flutter/material.dart';
import 'package:magic/magic.dart';

import '../../../app/controllers/product_type_controller.dart';

/// ProductTypeCreateView.
///
/// Generated by Magic CLI.
class ProductTypeCreateView extends MagicStatefulView<ProductTypeController> {
  const ProductTypeCreateView({super.key});

  @override
  State<ProductTypeCreateView> createState() => _ProductTypeCreateViewState();
}

class _ProductTypeCreateViewState
    extends
        MagicStatefulViewState<ProductTypeController, ProductTypeCreateView> {
  @override
  void onInit() {
    // Called after initState, controller is available
  }

  @override
  void onClose() {
    // Clean up resources
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('ProductTypeCreate')),
      body: const Center(child: Text('ProductTypeCreate')),
    );
  }
}
