import 'package:flutter/material.dart';
import 'package:magic/magic.dart';

import '../../../app/controllers/product_type_controller.dart';

/// ProductTypeEditView.
///
/// Generated by Magic CLI.
class ProductTypeEditView extends MagicStatefulView<ProductTypeController> {
  const ProductTypeEditView({super.key});

  @override
  State<ProductTypeEditView> createState() => _ProductTypeEditViewState();
}

class _ProductTypeEditViewState
    extends MagicStatefulViewState<ProductTypeController, ProductTypeEditView> {
  @override
  void onInit() {
    // Called after initState, controller is available
  }

  @override
  void onClose() {
    // Clean up resources
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('ProductTypeEdit')),
      body: const Center(child: Text('ProductTypeEdit')),
    );
  }
}
