import 'package:flutter/material.dart';
import 'package:magic/magic.dart';

import '../../../app/controllers/product_type_controller.dart';

/// ProductTypeIndexView.
///
/// Generated by Magic CLI.
class ProductTypeIndexView extends MagicStatefulView<ProductTypeController> {
  const ProductTypeIndexView({super.key});

  @override
  State<ProductTypeIndexView> createState() => _ProductTypeIndexViewState();
}

class _ProductTypeIndexViewState extends MagicStatefulViewState<
    ProductTypeController, ProductTypeIndexView> {
  @override
  void onInit() {
    // Called after initState, controller is available
  }

  @override
  void onClose() {
    // Clean up resources
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('ProductTypeIndex')),
      body: const Center(child: Text('ProductTypeIndex')),
    );
  }
}
