import 'package:flutter/material.dart';
import 'package:fluttersdk_magic/fluttersdk_magic.dart';

import '../../../app/controllers/product_type_controller.dart';

/// ProductTypeShowView.
///
/// Generated by Magic CLI.
class ProductTypeShowView extends MagicStatefulView<ProductTypeController> {
  const ProductTypeShowView({super.key});

  @override
  State<ProductTypeShowView> createState() => _ProductTypeShowViewState();
}

class _ProductTypeShowViewState
    extends MagicStatefulViewState<ProductTypeController, ProductTypeShowView> {
  @override
  void onInit() {
    // Called after initState, controller is available
  }

  @override
  void onClose() {
    // Clean up resources
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('ProductTypeShow'),
      ),
      body: const Center(
        child: Text('ProductTypeShow'),
      ),
    );
  }
}
